In [1]:
#set up
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')
data = ('/content/drive/My Drive/Colab Notebooks/SocialMediaPosts/MatchTextLength1204/01OrginalData/')
result = ('/content/drive/My Drive/Colab Notebooks/SocialMediaPosts/MatchTextLength1204/02DataForAnalysis/')

Mounted at /content/drive

#Health_social group: combine two csv. files together

## read the file

In [3]:
df1 = pd.read_csv(data + 'AARP_allTime_AgingHealthy100224.csv')
df1.head(2)

,creation_time,id,is_branded_content,lang,link_attachment.caption,link_attachment.description,link_attachment.link,link_attachment.name,media_type,modified_time,...,statistics.sad_count,statistics.share_count,statistics.views,statistics.views_date_last_refreshed,statistics.wow_count,surface.type,surface.id,surface.name,surface.username,text
0,2024-09-29T10:44:04-07:00,1087023169546137,False,en,aarp.org,Older adults want tech companies to focus more...,http://spr.ly/6189o2QDl,"AARP, Google Brainstorm Age-Friendly Smartphon...",links,2024-10-02T10:48:06-07:00,...,0.0,5,11818.0,2024-09-29,0.0,page,697104275802805,AARP,AARP,AARP volunteers gathered with user experience ...
1,2024-09-28T06:52:03-07:00,1527138294575882,False,en,aarp.org,​The actress riffs on getting her start in Hol...,http://spr.ly/6188o2Sts,"Taraji P. Henson, 54: ‘Money Doesn’t Make Your...",links,2024-10-02T10:53:20-07:00,...,0.0,7,7282.0,2024-09-29,0.0,page,697104275802805,AARP,AARP,Taraji P. Henson stars in the newly launched P...

In [ ]:
df2 = pd.read_csv(data + 'AmericanSocietyOnAging11142024.csv')
df2.head(2)

,activities,content_type,creation_time,id,is_branded_content,lang,link_attachment.caption,link_attachment.description,link_attachment.link,link_attachment.name,...,statistics.sad_count,statistics.share_count,statistics.views,statistics.views_date_last_refreshed,statistics.wow_count,surface.type,surface.id,surface.name,surface.username,text
0,NaN,photos,2024-11-14T11:00:29-08:00,806610294846439,False,en,NaN,NaN,NaN,NaN,...,0,1,NaN,NaN,0,page,1180080693173253,American Society on Aging,asaging,"Join us on Thursday, Dec. 5, for a live worksh..."
1,NaN,photos,2024-11-13T13:59:10-08:00,575663894992224,False,en,NaN,NaN,NaN,NaN,...,0,0,119.0,2024-11-14,0,page,1180080693173253,American Society on Aging,asaging,Team ASA has been at the Engaging With Aging 2...

## the basic info of each csv

In [ ]:
print("'AARP_allTime_AgingHealthy100224.csv':")
print("Number of Rows:", df1.shape[0])             # Get number of rows
print("Number of Columns:", df1.shape[1])          # Get number of columns

print("Column Names:", df1.columns.tolist())       # Get column names

'AARP_allTime_AgingHealthy100224.csv':
Number of Rows: 2848
Number of Columns: 33
Column Names: ['creation_time', 'id', 'is_branded_content', 'lang', 'link_attachment.caption', 'link_attachment.description', 'link_attachment.link', 'link_attachment.name', 'media_type', 'modified_time', 'multimedia', 'post_owner.type', 'post_owner.id', 'post_owner.name', 'post_owner.username', 'shared_post_id', 'statistics.angry_count', 'statistics.care_count', 'statistics.comment_count', 'statistics.haha_count', 'statistics.like_count', 'statistics.love_count', 'statistics.reaction_count', 'statistics.sad_count', 'statistics.share_count', 'statistics.views', 'statistics.views_date_last_refreshed', 'statistics.wow_count', 'surface.type', 'surface.id', 'surface.name', 'surface.username', 'text']

In [ ]:
print("'AmericanSocietyOnAging11142024.csv':")
print("Number of Rows:", df2.shape[0])             # Get number of rows
print("Number of Columns:", df2.shape[1])          # Get number of columns

print("Column Names:", df2.columns.tolist())       # Get column names

'AmericanSocietyOnAging11142024.csv':
Number of Rows: 223
Number of Columns: 35
Column Names: ['activities', 'content_type', 'creation_time', 'id', 'is_branded_content', 'lang', 'link_attachment.caption', 'link_attachment.description', 'link_attachment.link', 'link_attachment.name', 'match_type', 'modified_time', 'multimedia', 'post_owner.type', 'post_owner.id', 'post_owner.name', 'post_owner.username', 'shared_post_id', 'statistics.angry_count', 'statistics.care_count', 'statistics.comment_count', 'statistics.haha_count', 'statistics.like_count', 'statistics.love_count', 'statistics.reaction_count', 'statistics.sad_count', 'statistics.share_count', 'statistics.views', 'statistics.views_date_last_refreshed', 'statistics.wow_count', 'surface.type', 'surface.id', 'surface.name', 'surface.username', 'text']

In [ ]:
# Find columns that are in df1 but not in df2
columns_df1 = set(df1.columns)
columns_df2 = set(df2.columns)
diff_df1 = columns_df1 - columns_df2
print("Columns in df1 but not in df2:", diff_df1)

Columns in df1 but not in df2: {'media_type'}

In [ ]:
# Find columns that are in df2 but not in df1
diff_df2 = columns_df2 - columns_df1
print("Columns in df2 but not in df1:", diff_df2)

Columns in df2 but not in df1: {'activities', 'content_type', 'match_type'}

In [ ]:
# Find columns that are common to both DataFrames
common_columns = columns_df1.intersection(columns_df2) #use inetrsection ()
common_columns

{'creation_time',
 'id',
 'is_branded_content',
 'lang',
 'link_attachment.caption',
 'link_attachment.description',
 'link_attachment.link',
 'link_attachment.name',
 'modified_time',
 'multimedia',
 'post_owner.id',
 'post_owner.name',
 'post_owner.type',
 'post_owner.username',
 'shared_post_id',
 'statistics.angry_count',
 'statistics.care_count',
 'statistics.comment_count',
 'statistics.haha_count',
 'statistics.like_count',
 'statistics.love_count',
 'statistics.reaction_count',
 'statistics.sad_count',
 'statistics.share_count',
 'statistics.views',
 'statistics.views_date_last_refreshed',
 'statistics.wow_count',
 'surface.id',
 'surface.name',
 'surface.type',
 'surface.username',
 'text'}

## combine two CSV files （Keeps Only Common Columns）

In [ ]:
# Merge the two DataFrames based on the common columns：基于共同的列，将两个 DataFrame (df1 和 df2) 拼接在一起
merged_df = pd.concat([df1[common_columns], df2[common_columns]], ignore_index=True)

In [ ]:
merged_df.head(2)

,statistics.like_count,link_attachment.caption,statistics.love_count,post_owner.username,post_owner.name,modified_time,statistics.haha_count,surface.id,lang,text,...,link_attachment.description,statistics.views_date_last_refreshed,statistics.comment_count,creation_time,surface.type,statistics.care_count,statistics.reaction_count,statistics.wow_count,surface.name,statistics.sad_count
0,67.0,aarp.org,0.0,AARP,AARP,2024-10-02T10:48:06-07:00,0.0,697104275802805,en,AARP volunteers gathered with user experience ...,...,Older adults want tech companies to focus more...,2024-09-29,7,2024-09-29T10:44:04-07:00,page,0.0,67.0,0.0,AARP,0.0
1,96.0,aarp.org,3.0,AARP,AARP,2024-10-02T10:53:20-07:00,2.0,697104275802805,en,Taraji P. Henson stars in the newly launched P...,...,​The actress riffs on getting her start in Hol...,2024-09-29,10,2024-09-28T06:52:03-07:00,page,0.0,102.0,0.0,AARP,0.0

In [ ]:
print(df1.shape)
print(df2.shape)
print(merged_df.shape)

(2848, 33)
(223, 35)
(3071, 32)

In [ ]:
df1.shape[0] + df2.shape[0]== merged_df.shape[0]

True

## clean the "text" column: remove emoji, URLs, hashtags, and lowercase

In [ ]:
# Function to clean text
import re
import pandas as pd

def clean_text(text):
    # Check if the input is a string
    if isinstance(text, str):

        #Convert text to lowercase
        text = text.lower()

        # Remove new lines and extra spaces
        text = text.replace('\n', ' ').strip()

        # Remove hyperlinks (URLs)
        text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

        # Remove hashtags
        text = re.sub(r'#\w+', '', text)

        # Remove emojis (basic pattern to match most common emojis)
        emoji_pattern = re.compile("["
                                   u"\U0001F600-\U0001F64F"  # emoticons
                                   u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                                   u"\U0001F680-\U0001F6FF"  # transport & map symbols
                                   u"\U0001F700-\U0001F77F"  # alchemical symbols
                                   u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                                   u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                                   u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                                   u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                                   u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                                   u"\U00002702-\U000027B0"  # Dingbats
                                   u"\U000024C2-\U0001F251"
                                   "]+", flags=re.UNICODE)
        text = emoji_pattern.sub(r'', text)

        return text
    else:
        # Handle non-string values (e.g., return empty string or original value)
        return str(text) # or return '' or return text

In [ ]:
# Apply the cleaning function to the 'text' column
merged_df['clean_text'] = merged_df['text'].apply(clean_text)

In [ ]:
merged_df.head(2)

,statistics.like_count,link_attachment.caption,statistics.love_count,post_owner.username,post_owner.name,modified_time,statistics.haha_count,surface.id,lang,text,...,statistics.views_date_last_refreshed,statistics.comment_count,creation_time,surface.type,statistics.care_count,statistics.reaction_count,statistics.wow_count,surface.name,statistics.sad_count,clean_text
0,67.0,aarp.org,0.0,AARP,AARP,2024-10-02T10:48:06-07:00,0.0,697104275802805,en,AARP volunteers gathered with user experience ...,...,2024-09-29,7,2024-09-29T10:44:04-07:00,page,0.0,67.0,0.0,AARP,0.0,aarp volunteers gathered with user experience ...
1,96.0,aarp.org,3.0,AARP,AARP,2024-10-02T10:53:20-07:00,2.0,697104275802805,en,Taraji P. Henson stars in the newly launched P...,...,2024-09-29,10,2024-09-28T06:52:03-07:00,page,0.0,102.0,0.0,AARP,0.0,taraji p. henson stars in the newly launched p...

In [ ]:
# save the results to a new cvs. file
merged_df.to_csv(result + 'Health_social_clean_data.csv', index=False)

In [ ]:
print("Number of Rows:", merged_df.shape[0])             # Get number of rows
print("Number of Columns:", merged_df.shape[1])          # Get number of columns

print("Column Names:", merged_df.columns.tolist())       # Get column names

Number of Rows: 3071
Number of Columns: 33
Column Names: ['statistics.like_count', 'link_attachment.caption', 'statistics.love_count', 'post_owner.username', 'post_owner.name', 'modified_time', 'statistics.haha_count', 'surface.id', 'lang', 'text', 'post_owner.type', 'surface.username', 'statistics.views', 'link_attachment.link', 'shared_post_id', 'post_owner.id', 'statistics.angry_count', 'multimedia', 'is_branded_content', 'link_attachment.name', 'id', 'statistics.share_count', 'link_attachment.description', 'statistics.views_date_last_refreshed', 'statistics.comment_count', 'creation_time', 'surface.type', 'statistics.care_count', 'statistics.reaction_count', 'statistics.wow_count', 'surface.name', 'statistics.sad_count', 'clean_text']