# set up

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
data = ('/content/drive/My Drive/Colab Notebooks/SocialMediaPosts/MatchTextLength1204/01OrginalData')

Mounted at /content/drive

# read the data

In [ ]:
Delaware_AD = pd.read_csv(data + 'protocol_baycrest_delaware_mci_110624.csv')
Delaware_AD.head(2)

,Unnamed: 0,speaker,content,content_len,content_clean,content_clean_len,content_semi_clean,content_semi_len,task,PID,language,corpus,age,sex,CogDis,participant
0,0,PAR,right . 7839_8129,1.0,right,1.0,right,1.0,NaN,11312/a-00064235-1,eng,Baycrest,74;00.,female,MCI,Baycrest12257
1,1,PAR,oh_gosh . 25280_26230,1.0,oh gosh,2.0,oh gosh,2.0,Important_Event,11312/a-00064235-1,eng,Baycrest,74;00.,female,MCI,Baycrest12257

In [ ]:
Delaware_health = pd.read_csv(data + 'protocol_baycrest_delaware_control_110624.csv')
Delaware_health.head(2)

,Unnamed: 0,speaker,content,content_len,content_clean,content_clean_len,content_semi_clean,content_semi_len,task,PID,language,corpus,age,sex,CogDis,participant
0,0,PAR,yeah . 15875_16375,1.0,yeah,1.0,yeah,1.0,NaN,11312/a-00065467-1,eng,Delaware,84;00.,female,Control,97-1
1,1,PAR,well ‡ it looks like the window's open . 2559...,7.0,well it looks like the window's open,7.0,well it looks like the window's open,7.0,Cookie,11312/a-00065467-1,eng,Delaware,84;00.,female,Control,97-1

# define function to restore the punctatio

**Notice**:

> The "content_semi_clean" column has removed final punctuation like periods (.), we need to can restore them by checking the original content column and appending the appropriate punctuation to the cleaned text.

> The content column can sometimes include multiple types of metadata, such as [+ exc], timestamps (512280_513039), and annotations (e.g., [: Ella] [* s:r]). To restore punctuation to content_semi_clean reliably, we need to extract the meaningful text before any of these metadata and then append the punctuation correctly.

In [ ]:
# Function to restore punctuation

def restore_punctuation(row):
    original = row['content']  # Original content
    cleaned = row['content_semi_clean']  # Cleaned content

    # Step 1: Remove metadata like timestamps or brackets
    text_without_metadata = re.sub(r'\[.*?\]|\.*?\|\d+_\d+', '', original).strip()

    # Step 2: Check the last character of the meaningful text
    last_char = text_without_metadata[-1] if len(text_without_metadata) > 0 else ''

    # Step 3: If the last character is punctuation, append it to the cleaned text
    # Check if cleaned is a string before applying strip()
    if isinstance(cleaned, str) and last_char in ".!?":
        return cleaned.strip() + last_char

    # Step 4: If no punctuation is found or cleaned is not a string, return the cleaned value as is
    return cleaned

In [ ]:
#Apply the function to restore punctuation
Delaware_AD['text_clean'] = Delaware_AD.apply(restore_punctuation, axis=1)
Delaware_AD

,Unnamed: 0,speaker,content,content_len,content_clean,content_clean_len,content_semi_clean,content_semi_len,task,PID,language,corpus,age,sex,CogDis,participant,text_clean
0,0,PAR,right . 7839_8129,1.0,right,1.0,right,1.0,NaN,11312/a-00064235-1,eng,Baycrest,74;00.,female,MCI,Baycrest12257,right.
1,1,PAR,oh_gosh . 25280_26230,1.0,oh gosh,2.0,oh gosh,2.0,Important_Event,11312/a-00064235-1,eng,Baycrest,74;00.,female,MCI,Baycrest12257,oh gosh.
2,2,PAR,I don't really know . 26541_27821,4.0,I don't really know,4.0,I don't really know,4.0,Important_Event,11312/a-00064235-1,eng,Baycrest,74;00.,female,MCI,Baycrest12257,I don't really know.
3,3,PAR,I guess maybe when we moved to Port_Stanley . ...,8.0,I guess maybe when we moved to Port Stanley,9.0,I guess maybe when we moved to Port Stanley,9.0,Important_Event,11312/a-00064235-1,eng,Baycrest,74;00.,female,MCI,Baycrest12257,I guess maybe when we moved to Port Stanley.
4,4,PAR,&-um I'm Japanese . 33032_35222,3.0,um I'm Japanese,3.0,um I'm Japanese,3.0,Important_Event,11312/a-00064235-1,eng,Baycrest,74;00.,female,MCI,Baycrest12257,um I'm Japanese.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7687,7687,PAR,and spread the peanut butter . 760345_763385,5.0,and spread the peanut butter,5.0,and spread the peanut butter,5.0,Sandwich,11312/a-00078226-1,eng,Delaware,88;00.,female,MCI,23-1,and spread the peanut butter.
7688,7688,PAR,and then dot it with raisins . 763845_765825,6.0,and then dot it with raisins,6.0,and then dot it with raisins,6.0,Sandwich,11312/a-00078226-1,eng,Delaware,88;00.,female,MCI,23-1,and then dot it with raisins.
7689,7689,PAR,and cover it up . 767965_769625,4.0,and cover it up,4.0,and cover it up,4.0,Sandwich,11312/a-00078226-1,eng,Delaware,88;00.,female,MCI,23-1,and cover it up.
7690,7690,PAR,and slice it diagonally . 769625_770765,4.0,and slice it diagonally,4.0,and slice it diagonally,4.0,Sandwich,11312/a-00078226-1,eng,Delaware,88;00.,female,MCI,23-1,and slice it diagonally.
7691,7691,PAR,it is . [+ exc],3.0,it is,2.0,it is,2.0,Sandwich,11312/a-00078226-1,eng,Delaware,88;00.,female,MCI,23-1,it is.

In [ ]:
#  Apply the function to restore punctuation
Delaware_health['text_clean'] = Delaware_health.apply(restore_punctuation, axis=1)
Delaware_health

,Unnamed: 0,speaker,content,content_len,content_clean,content_clean_len,content_semi_clean,content_semi_len,task,PID,language,corpus,age,sex,CogDis,participant,text_clean
0,0,PAR,yeah . 15875_16375,1.0,yeah,1.0,yeah,1.0,NaN,11312/a-00065467-1,eng,Delaware,84;00.,female,Control,97-1,yeah.
1,1,PAR,well ‡ it looks like the window's open . 2559...,7.0,well it looks like the window's open,7.0,well it looks like the window's open,7.0,Cookie,11312/a-00065467-1,eng,Delaware,84;00.,female,Control,97-1,well it looks like the window's open.
2,2,PAR,and there are curtains pulled apart . 28165_3...,6.0,and there are curtains pulled apart,6.0,and there are curtains pulled apart,6.0,Cookie,11312/a-00065467-1,eng,Delaware,84;00.,female,Control,97-1,and there are curtains pulled apart.
3,3,PAR,"the housewife , I'm assuming , is doing the di...",8.0,the housewife I'm assuming is doing the dishes,8.0,the housewife I'm assuming is doing the dishes,8.0,Cookie,11312/a-00065467-1,eng,Delaware,84;00.,female,Control,97-1,the housewife I'm assuming is doing the dishes.
4,4,PAR,however the sink is running over . 34305_36565,6.0,however the sink is running over,6.0,however the sink is running over,6.0,Cookie,11312/a-00065467-1,eng,Delaware,84;00.,female,Control,97-1,however the sink is running over.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,3795,PAR,"and you say +""/. 424010_424500",3.0,and you say,3.0,and you say,3.0,Sandwich,11312/a-00055316-1,eng,Delaware,81;00.,female,Control,07-1,and you say.
3796,3796,PAR,"+"" here's your sandwich . 424760_425660",3.0,here's your sandwich,3.0,here's your sandwich,3.0,Sandwich,11312/a-00055316-1,eng,Delaware,81;00.,female,Control,07-1,here's your sandwich.
3797,3797,PAR,you put the bread away . 426140_427270,5.0,you put the bread away,5.0,you put the bread away,5.0,Sandwich,11312/a-00055316-1,eng,Delaware,81;00.,female,Control,07-1,you put the bread away.
3798,3798,PAR,peanut butter and the jelly away . 427570_429...,6.0,peanut butter and the jelly away,6.0,peanut butter and the jelly away,6.0,Sandwich,11312/a-00055316-1,eng,Delaware,81;00.,female,Control,07-1,peanut butter and the jelly away.
3799,3799,PAR,and you have a glass of milk and a peanut butt...,13.0,and you have a glass of milk and a peanut butt...,13.0,and you have a glass of milk and a peanut butt...,13.0,Sandwich,11312/a-00055316-1,eng,Delaware,81;00.,female,Control,07-1,and you have a glass of milk and a peanut butt...

In [ ]:
# save the results
Delaware_AD.to_csv(data + 'protocol_baycrest_delaware_mci_110624.csv', index=False)

In [ ]:
# save the results
Delaware_health.to_csv(data + 'protocol_baycrest_delaware_control_110624.csv', index=False)

# (ignore this part)Test/try: clean the "cotent" column ---->failed!

In [ ]:
def clean_text(content):
    # Step 1: Remove bracket annotations like [//] or [<text>]
    content = re.sub(r'\[.*?\]', '', content)  # Removes any text inside brackets

    # Step 2: Remove ampersand annotations like &+m or +//
    content = re.sub(r'&\S*', '', content)

    # Step 3: Remove timestamps or numeric patterns
    content = re.sub(r'\b\d+\b', '', content)  # Removes standalone numbers (e.g., timestamps)

    # Step 4: Normalize spaces and punctuation
    content = re.sub(r'\s+', ' ', content)  # Replace multiple spaces with a single space
    content = content.strip()  # Remove leading/trailing spaces

    # Step 5: Ensure meaningful punctuation
    if content and content[-1] not in '.!?':
        content += '.'  # Add a period if no punctuation exists

    return content

In [ ]:
df = Delaware_AD[['participant', 'content', 'content_semi_clean']]
df

,participant,content,content_semi_clean
0,Baycrest12257,right . 7839_8129,right
1,Baycrest12257,oh_gosh . 25280_26230,oh gosh
2,Baycrest12257,I don't really know . 26541_27821,I don't really know
3,Baycrest12257,I guess maybe when we moved to Port_Stanley . ...,I guess maybe when we moved to Port Stanley
4,Baycrest12257,&-um I'm Japanese . 33032_35222,um I'm Japanese
...,...,...,...
7687,23-1,and spread the peanut butter . 760345_763385,and spread the peanut butter
7688,23-1,and then dot it with raisins . 763845_765825,and then dot it with raisins
7689,23-1,and cover it up . 767965_769625,and cover it up
7690,23-1,and slice it diagonally . 769625_770765,and slice it diagonally
7691,23-1,it is . [+ exc],it is

In [ ]:
# Apply cleaning function to the DataFrame
df['content_clean'] = df['content'].apply(clean_text)

<ipython-input-44-8bfc0a0ef7d9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content_clean'] = df['content'].apply(clean_text)

In [ ]:
df

,participant,content,content_semi_clean,content_clean
0,Baycrest12257,right . 7839_8129,right,right . 7839_8129.
1,Baycrest12257,oh_gosh . 25280_26230,oh gosh,oh_gosh . 25280_26230.
2,Baycrest12257,I don't really know . 26541_27821,I don't really know,I don't really know . 26541_27821.
3,Baycrest12257,I guess maybe when we moved to Port_Stanley . ...,I guess maybe when we moved to Port Stanley,I guess maybe when we moved to Port_Stanley . ...
4,Baycrest12257,&-um I'm Japanese . 33032_35222,um I'm Japanese,I'm Japanese . 33032_35222.
...,...,...,...,...
7687,23-1,and spread the peanut butter . 760345_763385,and spread the peanut butter,and spread the peanut butter . 760345_763385.
7688,23-1,and then dot it with raisins . 763845_765825,and then dot it with raisins,and then dot it with raisins . 763845_765825.
7689,23-1,and cover it up . 767965_769625,and cover it up,and cover it up . 767965_769625.
7690,23-1,and slice it diagonally . 769625_770765,and slice it diagonally,and slice it diagonally . 769625_770765.
7691,23-1,it is . [+ exc],it is,it is .