# set up

In [ ]:
#set up
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
data = ('/content/drive/My Drive/Colab Notebooks/SocialMediaPosts/MatchTextLength1204/02DataForAnalysis/')
result = ('/content/drive/My Drive/Colab Notebooks/SocialMediaPosts/MatchTextLength1204/03Results/')
brief = ('/content/drive/My Drive/Colab Notebooks/SocialMediaPosts/MatchTextLength1204/04DataForR/')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Example: sentiment analysis with VADER

In [ ]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (2024.8.30)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 2.3 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
# a long continous string
text = "Shocking new data has shown that people living with undiagnosed dementia attend A&E three times more than those without the condition, adding up to over 520,000 visits each year.  Yesterday we shared the results of a new study which demonstrate the impact dementia has on our healthcare systems. This includes finding that people with undiagnosed dementia, on average, attend A&E more than people diagnosed with mild, moderate and severe dementia.  Gail cares for her father John who was diagnosed with Lewy Body dementia last year. While waiting for a diagnosis, John attended A&E several times.  ‘In December 2021, dad was diagnosed with a very slight cognitive impairment. He was losing his keys or misplacing his wallet. He lost interest in listening to music and became quite nervous about driving to new places.  ‘In May 2022, dad fell backwards in the shower. There was blood all over the bathroom floor and we took dad to A&E. He didn’t require any stitches, and the CT scan they performed was clear.  ‘Then dad got mixed up at a roundabout that he used every day and went the wrong way around the roundabout. He never drove the car again.  ‘We went to see the GP who did a memory test. I thought dad didn’t do well at all and was very worried, but the GP felt he was suffering from anxiety. In November we got a referral to the Memory Clinic.  ‘In February 2023, dad had another collapse, where he suddenly fell backwards onto the pavement. He went to A&E and had a CT scan. The results were clear again with just a normal ageing brain.  ‘The following month, dad had a diagnostic assessment where the diagnosis was dementia. Looking back the diagnosis experience was horrendous. Dad had every scan going - MRIs, CT scans, CT scans with dye - but doctors didn’t have an answer because the scans were clear. We didn't have the right type of scan to detect dad's dementia type.’  We’re calling on the Government to increase access to early and accurate dementia diagnosis to help families manage symptoms and avoid reaching avoidable crisis point. Early diagnosis is crucial for allowing people to access interventions to manage their symptoms and stay well for longer."

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [ ]:
analyzer = SentimentIntensityAnalyzer()

In [ ]:
scores = analyzer.polarity_scores(text)
scores

{'neg': 0.089, 'neu': 0.847, 'pos': 0.064, 'compound': -0.907}

# Define a function to get sentiment scores and classify sentiment

In [ ]:
# Define a function to get sentiment scores and classify sentiment
def analyze_VADER_sentiment(text):
    # Check if the input is a string; if not, convert it to a string.
    if not isinstance(text, str):
        text = str(text)

    scores = analyzer.polarity_scores(text)

    # Classify sentiment based on the compound score
    if scores['compound'] >= 0.05:
        sentiment = 'Positive'
    elif scores['compound'] <= -0.05:
        sentiment = 'Negative'
    else:
        sentiment = 'Neutral'

    return pd.Series([scores['neg'], scores['neu'], scores['pos'], scores['compound'], sentiment])

# AD (social media group)

In [ ]:
#read the data
ad_social = pd.read_csv(data + 'AD_social_clean_data_RemovedCluster246.csv',engine='python')
ad_social

,Unnamed: 0,idx,creation_time,id,is_branded_content,lang,link_attachment.caption,link_attachment.description,link_attachment.link,link_attachment.name,...,statistics.views,statistics.views_date_last_refreshed,statistics.wow_count,surface.type,surface.id,surface.name,surface.username,text,clean_text,cluster
0,0,0,2024-09-16T08:00:05-07:00,1.194189e+15,False,en,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,Shocking new data has shown that people living...,shocking new data has shown that people living...,3.0
1,1,1,2024-09-14T13:00:08-07:00,8.765100e+14,False,en,NaN,NaN,NaN,NaN,...,17947.0,2024-09-14,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,‘I never imagined dementia impacting our lives...,‘i never imagined dementia impacting our lives...,3.0
2,2,2,2024-09-13T01:00:06-07:00,5.042727e+14,False,en,NaN,NaN,NaN,NaN,...,22868.0,2024-09-14,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,We know there is a long way to go when it come...,we know there is a long way to go when it come...,1.0
3,3,3,2024-09-12T01:00:01-07:00,1.286549e+15,False,en,NaN,NaN,NaN,NaN,...,25540.0,2024-09-14,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,‘It felt like we had just been given a label a...,‘it felt like we had just been given a label a...,3.0
4,4,4,2024-09-09T05:00:01-07:00,1.231950e+15,False,en,NaN,NaN,NaN,NaN,...,43520.0,2024-09-14,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,"‘We had all heard about dementia, but we never...","‘we had all heard about dementia, but we never...",3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2675,2675,2675,2010-04-15T07:17:43-07:00,5.187244e+14,False,NaN,alzheimers.org.uk,Alzheimer's Society called on our political pa...,http://www.alzheimers.org.uk/site/scripts/docu...,What are the three main political parties’ ele...,...,NaN,NaN,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,Want to know what the major parties are saying...,want to know what the major parties are saying...,0.0
2676,2676,2676,2010-04-01T07:54:09-07:00,3.725374e+15,False,NaN,alzheimers.org.uk,NaN,http://www.alzheimers.org.uk/site/scripts/docu...,www.alzheimers.org.uk,...,NaN,NaN,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,Don't miss out on one of the best races in the...,don't miss out on one of the best races in the...,5.0
2677,2677,2677,2010-03-31T08:29:41-07:00,8.861507e+14,False,NaN,forum.alzheimers.org.uk,"Many Happy Returns, TP Support for people with...",http://forum.alzheimers.org.uk/showthread.php?...,"Many Happy Returns, TP - Talking Point",...,NaN,NaN,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,'Talking Point' our online forum is 7 years ol...,'talking point' our online forum is 7 years ol...,8.0
2678,2678,2678,2009-09-21T04:18:01-07:00,1.517941e+15,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,Thanks to everyone that took part in this week...,thanks to everyone that took part in this week...,5.0
2679,2679,2679,2008-02-28T07:29:38-08:00,8.267263e+14,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,page,1.604582e+15,Alzheimer's Society,alzheimerssocietyuk,Young people talk about their experiences of h...,young people talk about their experiences of h...,1.0

In [ ]:
ad_social.shape

(2680, 37)

In [ ]:
# Apply the sentiment analysis function to the 'clean_text' column
ad_social[['VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']] = ad_social['clean_text'].apply(analyze_VADER_sentiment)
ad_social

,Unnamed: 0,idx,creation_time,id,is_branded_content,lang,link_attachment.caption,link_attachment.description,link_attachment.link,link_attachment.name,...,surface.name,surface.username,text,clean_text,cluster,VADER_neg,VADER_neu,VADER_pos,VADER_compound,VADER_sentiment
0,0,0,2024-09-16T08:00:05-07:00,1.194189e+15,False,en,NaN,NaN,NaN,NaN,...,Alzheimer's Society,alzheimerssocietyuk,Shocking new data has shown that people living...,shocking new data has shown that people living...,3.0,0.089,0.847,0.064,-0.9070,Negative
1,1,1,2024-09-14T13:00:08-07:00,8.765100e+14,False,en,NaN,NaN,NaN,NaN,...,Alzheimer's Society,alzheimerssocietyuk,‘I never imagined dementia impacting our lives...,‘i never imagined dementia impacting our lives...,3.0,0.020,0.815,0.165,0.9947,Positive
2,2,2,2024-09-13T01:00:06-07:00,5.042727e+14,False,en,NaN,NaN,NaN,NaN,...,Alzheimer's Society,alzheimerssocietyuk,We know there is a long way to go when it come...,we know there is a long way to go when it come...,1.0,0.030,0.928,0.042,0.1531,Positive
3,3,3,2024-09-12T01:00:01-07:00,1.286549e+15,False,en,NaN,NaN,NaN,NaN,...,Alzheimer's Society,alzheimerssocietyuk,‘It felt like we had just been given a label a...,‘it felt like we had just been given a label a...,3.0,0.107,0.745,0.148,0.9859,Positive
4,4,4,2024-09-09T05:00:01-07:00,1.231950e+15,False,en,NaN,NaN,NaN,NaN,...,Alzheimer's Society,alzheimerssocietyuk,"‘We had all heard about dementia, but we never...","‘we had all heard about dementia, but we never...",3.0,0.154,0.722,0.124,-0.9318,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2675,2675,2675,2010-04-15T07:17:43-07:00,5.187244e+14,False,NaN,alzheimers.org.uk,Alzheimer's Society called on our political pa...,http://www.alzheimers.org.uk/site/scripts/docu...,What are the three main political parties’ ele...,...,Alzheimer's Society,alzheimerssocietyuk,Want to know what the major parties are saying...,want to know what the major parties are saying...,0.0,0.000,0.676,0.324,0.8221,Positive
2676,2676,2676,2010-04-01T07:54:09-07:00,3.725374e+15,False,NaN,alzheimers.org.uk,NaN,http://www.alzheimers.org.uk/site/scripts/docu...,www.alzheimers.org.uk,...,Alzheimer's Society,alzheimerssocietyuk,Don't miss out on one of the best races in the...,don't miss out on one of the best races in the...,5.0,0.060,0.601,0.339,0.9010,Positive
2677,2677,2677,2010-03-31T08:29:41-07:00,8.861507e+14,False,NaN,forum.alzheimers.org.uk,"Many Happy Returns, TP Support for people with...",http://forum.alzheimers.org.uk/showthread.php?...,"Many Happy Returns, TP - Talking Point",...,Alzheimer's Society,alzheimerssocietyuk,'Talking Point' our online forum is 7 years ol...,'talking point' our online forum is 7 years ol...,8.0,0.000,1.000,0.000,0.0000,Neutral
2678,2678,2678,2009-09-21T04:18:01-07:00,1.517941e+15,False,NaN,NaN,NaN,NaN,NaN,...,Alzheimer's Society,alzheimerssocietyuk,Thanks to everyone that took part in this week...,thanks to everyone that took part in this week...,5.0,0.000,0.774,0.226,0.7906,Positive
2679,2679,2679,2008-02-28T07:29:38-08:00,8.267263e+14,False,NaN,NaN,NaN,NaN,NaN,...,Alzheimer's Society,alzheimerssocietyuk,Young people talk about their experiences of h...,young people talk about their experiences of h...,1.0,0.000,1.000,0.000,0.0000,Neutral

In [ ]:
ad_social = ad_social.drop(columns=['Unnamed: 0'])
ad_social.head(2)

,idx,creation_time,id,is_branded_content,lang,link_attachment.caption,link_attachment.description,link_attachment.link,link_attachment.name,media_type,...,surface.name,surface.username,text,clean_text,cluster,VADER_neg,VADER_neu,VADER_pos,VADER_compound,VADER_sentiment
0,0,2024-09-16T08:00:05-07:00,1.194189e+15,False,en,NaN,NaN,NaN,NaN,albums,...,Alzheimer's Society,alzheimerssocietyuk,Shocking new data has shown that people living...,shocking new data has shown that people living...,3.0,0.089,0.847,0.064,-0.9070,Negative
1,1,2024-09-14T13:00:08-07:00,8.765100e+14,False,en,NaN,NaN,NaN,NaN,albums,...,Alzheimer's Society,alzheimerssocietyuk,‘I never imagined dementia impacting our lives...,‘i never imagined dementia impacting our lives...,3.0,0.020,0.815,0.165,0.9947,Positive

In [49]:
# save the results to a new cvs. file
ad_social.to_csv(result + 'AD_social_result.csv', index=False)

let us also save the results in a new df.

In [ ]:
df1 = ad_social[['idx', 'id',	'clean_text','VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']]
df1.head(2)

,idx,id,clean_text,VADER_neg,VADER_neu,VADER_pos,VADER_compound,VADER_sentiment
0,0,1.194189e+15,shocking new data has shown that people living...,0.089,0.847,0.064,-0.9070,Negative
1,1,8.765100e+14,‘i never imagined dementia impacting our lives...,0.020,0.815,0.165,0.9947,Positive

In [ ]:
# save the results to a new cvs. file
df1.to_csv(brief + 'AD_social_brief_result.csv', index=False)

# Health (social media group)

In [ ]:
#read the data
health_social = pd.read_csv( data + 'Health_social_clean_data.csv',engine='python')
#health_social.insert(0, 'idx', health_social.index) #Add a new column named "index" using the existing DataFrame index
health_social

,idx,statistics.like_count,link_attachment.caption,statistics.love_count,post_owner.username,post_owner.name,modified_time,statistics.haha_count,surface.id,lang,...,statistics.views_date_last_refreshed,statistics.comment_count,creation_time,surface.type,statistics.care_count,statistics.reaction_count,statistics.wow_count,surface.name,statistics.sad_count,clean_text
0,0,67.0,aarp.org,0.0,AARP,AARP,2024-10-02T10:48:06-07:00,0.0,6.971043e+14,en,...,2024-09-29,7.0,2024-09-29T10:44:04-07:00,page,0.0,67.0,0.0,AARP,0.0,aarp volunteers gathered with user experience ...
1,1,96.0,aarp.org,3.0,AARP,AARP,2024-10-02T10:53:20-07:00,2.0,6.971043e+14,en,...,2024-09-29,10.0,2024-09-28T06:52:03-07:00,page,0.0,102.0,0.0,AARP,0.0,taraji p. henson stars in the newly launched p...
2,2,488.0,NaN,51.0,AARP,AARP,2024-10-02T10:05:42-07:00,2.0,6.971043e+14,en,...,2024-09-29,31.0,2024-09-27T13:37:00-07:00,page,0.0,542.0,0.0,AARP,1.0,howie mandel found his purpose doing standup c...
3,3,113.0,NaN,19.0,AARP,AARP,2024-10-01T06:34:55-07:00,0.0,6.971043e+14,en,...,2024-09-29,9.0,2024-09-27T12:19:04-07:00,page,0.0,133.0,1.0,AARP,0.0,who is the highest-grossing actor? samuel l. j...
4,4,318.0,NaN,74.0,AARP,AARP,2024-09-24T13:01:49-07:00,1.0,6.971043e+14,en,...,2024-09-29,47.0,2024-09-24T12:58:01-07:00,page,0.0,393.0,0.0,AARP,0.0,legendary drummer and singer sheila e. has man...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3068,3068,1.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-29T19:03:18-07:00,0.0,1.180081e+15,en,...,2024-11-04,0.0,2024-05-17T12:24:02-07:00,page,0.0,1.0,0.0,American Society on Aging,0.0,with more than 80% of older adults living with...
3069,3069,0.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-28T05:46:32-07:00,0.0,1.180081e+15,en,...,2024-11-04,0.0,2024-05-16T10:36:02-07:00,page,0.0,0.0,0.0,American Society on Aging,0.0,"neither the systems serving older adults, nor ..."
3070,3070,0.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-28T05:45:39-07:00,0.0,1.180081e+15,en,...,2024-11-04,0.0,2024-05-15T14:57:24-07:00,page,0.0,0.0,0.0,American Society on Aging,0.0,"in the fall of 2023, more than 40 indigenous e..."
3071,3071,2.0,NaN,0.0,asaging,American Society on Aging,2024-09-07T06:58:41-07:00,0.0,1.180081e+15,en,...,2024-11-10,3.0,2024-05-14T13:08:25-07:00,page,0.0,2.0,0.0,American Society on Aging,0.0,webinar tomorrow | learn more about later-life...
3072,3072,3.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-28T05:45:01-07:00,0.0,1.180081e+15,en,...,2024-11-04,0.0,2024-05-14T09:02:39-07:00,page,0.0,3.0,0.0,American Society on Aging,0.0,you may have heard that the federal government...

In [ ]:
health_social.shape

(3073, 34)

In [ ]:
# Apply the sentiment analysis function to the 'clean_text' column
health_social[['VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']] = health_social['clean_text'].apply(analyze_VADER_sentiment)
health_social

,idx,statistics.like_count,link_attachment.caption,statistics.love_count,post_owner.username,post_owner.name,modified_time,statistics.haha_count,surface.id,lang,...,statistics.reaction_count,statistics.wow_count,surface.name,statistics.sad_count,clean_text,VADER_neg,VADER_neu,VADER_pos,VADER_compound,VADER_sentiment
0,0,67.0,aarp.org,0.0,AARP,AARP,2024-10-02T10:48:06-07:00,0.0,6.971043e+14,en,...,67.0,0.0,AARP,0.0,aarp volunteers gathered with user experience ...,0.000,0.793,0.207,0.8807,Positive
1,1,96.0,aarp.org,3.0,AARP,AARP,2024-10-02T10:53:20-07:00,2.0,6.971043e+14,en,...,102.0,0.0,AARP,0.0,taraji p. henson stars in the newly launched p...,0.060,0.750,0.190,0.9393,Positive
2,2,488.0,NaN,51.0,AARP,AARP,2024-10-02T10:05:42-07:00,2.0,6.971043e+14,en,...,542.0,0.0,AARP,1.0,howie mandel found his purpose doing standup c...,0.000,0.751,0.249,0.9313,Positive
3,3,113.0,NaN,19.0,AARP,AARP,2024-10-01T06:34:55-07:00,0.0,6.971043e+14,en,...,133.0,1.0,AARP,0.0,who is the highest-grossing actor? samuel l. j...,0.000,1.000,0.000,0.0000,Neutral
4,4,318.0,NaN,74.0,AARP,AARP,2024-09-24T13:01:49-07:00,1.0,6.971043e+14,en,...,393.0,0.0,AARP,0.0,legendary drummer and singer sheila e. has man...,0.019,0.914,0.067,0.5423,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3068,3068,1.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-29T19:03:18-07:00,0.0,1.180081e+15,en,...,1.0,0.0,American Society on Aging,0.0,with more than 80% of older adults living with...,0.063,0.871,0.065,0.0258,Neutral
3069,3069,0.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-28T05:46:32-07:00,0.0,1.180081e+15,en,...,0.0,0.0,American Society on Aging,0.0,"neither the systems serving older adults, nor ...",0.000,0.889,0.111,0.6249,Positive
3070,3070,0.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-28T05:45:39-07:00,0.0,1.180081e+15,en,...,0.0,0.0,American Society on Aging,0.0,"in the fall of 2023, more than 40 indigenous e...",0.000,0.955,0.045,0.2960,Positive
3071,3071,2.0,NaN,0.0,asaging,American Society on Aging,2024-09-07T06:58:41-07:00,0.0,1.180081e+15,en,...,2.0,0.0,American Society on Aging,0.0,webinar tomorrow | learn more about later-life...,0.000,1.000,0.000,0.0000,Neutral
3072,3072,3.0,generations.asaging.org,0.0,asaging,American Society on Aging,2024-05-28T05:45:01-07:00,0.0,1.180081e+15,en,...,3.0,0.0,American Society on Aging,0.0,you may have heard that the federal government...,0.000,1.000,0.000,0.0000,Neutral

In [50]:
# save the results to a new cvs. file
health_social.to_csv(result + 'Health_social_result.csv', index=False)

In [ ]:
df2 = health_social[['idx', 'id',	'clean_text','VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']]
df2.head(2)

,idx,id,clean_text,VADER_neg,VADER_neu,VADER_pos,VADER_compound,VADER_sentiment
0,0,1.087023e+15,aarp volunteers gathered with user experience ...,0.00,0.793,0.207,0.8807,Positive
1,1,1.527138e+15,taraji p. henson stars in the newly launched p...,0.06,0.750,0.190,0.9393,Positive

In [ ]:
# save the results to a new cvs. file
df2.to_csv(brief + 'Health_social_brief_result.csv', index=False)

# AD (clinical group)

In [ ]:
#read the data
ad_clinical = pd.read_csv(data + 'AD_clinical_clean_data.csv',engine='python')
ad_clinical.insert(0, 'idx', ad_clinical.index) #Add a new column named "index" using the existing DataFrame index
ad_clinical.head(2)

,idx,PAR,corpus,diag,age,gender,clean_text
0,0,dementia-001-2,He_Hinzen,ModerateAD,59,male,mhm . there's a young boy going in a cookie ja...
1,1,dementia-003-0,He_Hinzen,MildAD,56,male,here's a cookie jar . and the lid is off the c...

In [ ]:
ad_clinical.shape

(195, 7)

In [ ]:
# Apply the sentiment analysis function to the 'clean_text' column
ad_clinical[['VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']] = ad_clinical['clean_text'].apply(analyze_VADER_sentiment)
ad_clinical

,idx,PAR,corpus,diag,age,gender,clean_text,VADER_neg,VADER_neu,VADER_pos,VADER_compound,VADER_sentiment
0,0,dementia-001-2,He_Hinzen,ModerateAD,59,male,mhm . there's a young boy going in a cookie ja...,0.029,0.951,0.020,-0.0258,Neutral
1,1,dementia-003-0,He_Hinzen,MildAD,56,male,here's a cookie jar . and the lid is off the c...,0.013,0.916,0.071,0.9161,Positive
2,2,dementia-005-2,He_Hinzen,MildAD,55,male,okay he's falling off a chair . she's running ...,0.222,0.723,0.055,-0.5812,Negative
3,3,dementia-007-3,He_Hinzen,ModerateAD,75,female,well the girl is telling the boy to get the co...,0.054,0.893,0.053,-0.0129,Neutral
4,4,dementia-010-0,He_Hinzen,MildAD,66,male,oh boy . wowie the boy's going up on a cookiej...,0.006,0.949,0.044,0.8146,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...
190,190,Baycrest11976,Baycrest,MCI,88;00.,male,alright. you're going. uh the reason I'm laugh...,0.042,0.869,0.089,0.9919,Positive
191,191,Baycrest12257,Baycrest,MCI,74;00.,female,right. oh gosh. I don't really know. I guess m...,0.024,0.898,0.078,0.9979,Positive
192,192,Baycrest12813,Baycrest,MCI,66;00.,male,thinking back tell you a story. I have an inte...,0.050,0.844,0.105,0.9990,Positive
193,193,Baycrest7352,Baycrest,MCI,71;00.,female,can you repeat the question? okay well as I si...,0.034,0.863,0.103,0.9819,Positive
194,194,Baycrest8961,Baycrest,MCI,82;00.,male,mhm. yeah. um yes I can remember at least when...,0.051,0.875,0.074,0.9966,Positive

In [51]:
# save the results to a new cvs. file
ad_clinical.to_csv(result + 'AD_clinical_result.csv', index=False)

In [ ]:
#df3 = ad_clinical[['idx', 'PAR', 'clean_text','VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']]
#df3.head(2)

In [ ]:
# save the results to a new cvs. file
# df3.to_csv(result + 'AD_clinical_brief_result.csv', index=False)

# Health (clinical group)

In [ ]:
#read the data
health_clinical = pd.read_csv(data + 'Health_clinical_clean_data.csv',engine='python')
health_clinical.insert(0, 'idx', health_clinical.index) #Add a new column named "index" using the existing DataFrame index
health_clinical

,idx,PAR,corpus,diag,age,gender,clean_text
0,0,control-002-0,He_Hinzen,Control,58,female,the scene is in the kitchen . the mother is wi...
1,1,control-013-0,He_Hinzen,Control,62,female,somebody's getting cookies out of the cookie j...
2,2,control-015-1,He_Hinzen,Control,67,female,okay . a little boy is stepping on a stool tha...
3,3,control-017-4,He_Hinzen,Control,71,female,are you ready ? well the sink is overflowing ....
4,4,control-021-1,He_Hinzen,Control,74,female,okay . the mother's washing the dishes and the...
...,...,...,...,...,...,...,...
99,99,94-1,Delaware,Control,68;00.,female,yep
100,100,96-1,Delaware,Control,61;00.,female,yep
101,101,97-1,Delaware,Control,84;00.,female,yeah
102,102,98-1,Delaware,Control,63;00.,female,okay
103,103,99-1,Delaware,Control,73;00.,female,I see a woman drying dishes with her sink over...

In [ ]:
health_clinical.shape

(104, 7)

In [54]:
# Apply the sentiment analysis function to the 'clean_text' column
health_clinical[['VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']] = health_clinical['clean_text'].apply(analyze_VADER_sentiment)
health_clinical

,idx,PAR,corpus,diag,age,gender,clean_text,VADER_neg,VADER_neu,VADER_pos,VADER_compound,VADER_sentiment
0,0,control-002-0,He_Hinzen,Control,58,female,the scene is in the kitchen . the mother is wi...,0.010,0.925,0.064,0.7579,Positive
1,1,control-013-0,He_Hinzen,Control,62,female,somebody's getting cookies out of the cookie j...,0.020,0.980,0.000,-0.2547,Negative
2,2,control-015-1,He_Hinzen,Control,67,female,okay . a little boy is stepping on a stool tha...,0.029,0.923,0.048,0.4447,Positive
3,3,control-017-4,He_Hinzen,Control,71,female,are you ready ? well the sink is overflowing ....,0.090,0.827,0.083,-0.7882,Negative
4,4,control-021-1,He_Hinzen,Control,74,female,okay . the mother's washing the dishes and the...,0.007,0.963,0.030,0.4967,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...
99,99,94-1,Delaware,Control,68;00.,female,yep,0.000,0.000,1.000,0.2960,Positive
100,100,96-1,Delaware,Control,61;00.,female,yep,0.000,0.000,1.000,0.2960,Positive
101,101,97-1,Delaware,Control,84;00.,female,yeah,0.000,0.000,1.000,0.2960,Positive
102,102,98-1,Delaware,Control,63;00.,female,okay,0.000,0.000,1.000,0.2263,Positive
103,103,99-1,Delaware,Control,73;00.,female,I see a woman drying dishes with her sink over...,0.000,1.000,0.000,0.0000,Neutral

In [55]:
# save the results to a new cvs. file
health_clinical.to_csv(result + 'Health_clinical_result.csv', index=False)

In [ ]:
#df4 = health_clinical[['idx', 'PAR', 'clean_text','VADER_neg', 'VADER_neu', 'VADER_pos', 'VADER_compound', 'VADER_sentiment']]
#df4.head(2)

In [ ]:
#df4.to_csv(result + 'Health_clinical_NLP_result.csv', index=False)